(0.002) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.001) SET SQL_AUTO_IS_NULL = 0; args=None
(0.001) SELECT VERSION(); args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.002) SHOW FULL TABLES; args=None
(0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
(0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.002) SET SQL_AUTO_IS_NULL = 0; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.002) SHOW FULL TABLES; args=None
(0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
"GET / HTTP/1.1" 302 0
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.000) SELECT VERSION(); args=None
(0.001) SET SQL_AUTO_IS_NULL = 0; args=None
(0.002) SHOW FULL TABLES; args=None
(0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
"GET / HTTP/1.1" 302 0
"GET /updateOp/login HTTP/1.1" 200 3274
"GET /static/dist/css/sb-admin-2.css HTTP/1.1" 200 5593
"GET /static/metisMenu/dist/metisMenu.min.css HTTP/1.1" 200 781
"GET /static/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 29062
"GET /static/js/bootstrap.min.js HTTP/1.1" 200 36868
"GET /static/metisMenu/dist/metisMenu.min.js HTTP/1.1" 200 1879
"GET /static/js/jquery.min.js HTTP/1.1" 200 84380
"GET /static/js/sb-admin-2.js HTTP/1.1" 200 1181
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 121260
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'grappelli.urls' from '/usr/local/lib/python2.7/site-packages/grappelli/urls.pyc'> (None:None) ^grappelli/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'updateOp.urls' from '/home/docker/code/itinfo/updateOp/urls.pyc'> (None:None) ^updateop/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'portmap.urls' from '/home/docker/code/itinfo/portmap/urls.pyc'> (None:None) ^portmap/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'appinfo.urls' from '/home/docker/code/itinfo/appinfo/urls.pyc'> (None:None) ^appinfo/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'ipresource.urls' from '/home/docker/code/itinfo/ipresource/urls.pyc'> (None:None) ^ipresource/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'dbinfo.urls' from '/home/docker/code/itinfo/dbinfo/urls.pyc'> (None:None) ^dbinfo/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'addressbook.urls' from '/home/docker/code/itinfo/addressbook/urls.pyc'> (None:None) ^addressbook/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u"<RegexURLResolver <module 'shortcut.urls' from '/home/docker/code/itinfo/shortcut/urls.pyc'> (None:None) ^shortcut/>"
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3559
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
Exception while resolving variable 'debug' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [debug] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f9398e907d0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398f7ea90>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e91390>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398f7e710>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398fbbdd0>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: javascripts. Contents: [<TextNode: u\'\\n        <script type="te\'>, <django.template.defaulttags.FilterNode object at 0x7f9398e9ad10>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.FilterNode object at 0x7f9398e9ae10>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.URLNode object at 0x7f9398eba7d0>, <TextNode: u\'",\\n                MODEL_\'>, <IfNode>, <TextNode: u\',\\n                DATE_FO\'>, <django.template.library.SimpleNode object at 0x7f9398ebaa50>, <TextNode: u\'",\\n                TIME_F\'>, <django.template.library.SimpleNode object at 0x7f9398ebaad0>, <TextNode: u\'",\\n                DATETI\'>, <django.template.library.SimpleNode object at 0x7f9398ebab50>, <TextNode: u\'";\\n        </script>\\n    \'>, <django.template.library.SimpleNode object at 0x7f9398ebabd0>, <TextNode: u\'" type="text/javascript">\'>, <django.template.library.SimpleNode object at 0x7f9398ebac90>, <TextNode: u\'" type="text/javascript">\'>, <IfNode>, <TextNode: u\'\\n        <script type="te\'>]>}]'
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f9398e907d0>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398f7ea90>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e91390>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398f7e710>, u'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/', 'available_apps': [], 'site_name': '192.168.1.34:8000', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, 'site': <django.contrib.sites.requests.RequestSite object at 0x7f9398fbbdd0>, 'next': u'/admin/', 'site_title': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u'LANGUAGE_CODE': 'zh-Hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False}]"
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f9398e907d0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398f7ea90>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e91390>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398f7e710>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398fbbdd0>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}]'
Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f9398e907d0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398f7ea90>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e91390>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398f7e710>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398fbbdd0>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}, {\'block\': <Block Node: navigation. Contents: [<TextNode: u\'\\n                        \'>, <Block Node: branding. Contents: []>, <TextNode: u\'\\n                        \'>, <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>, <TextNode: u\'\\n                        \'>, <Block Node: user-tools. Contents: [<TextNode: u\'\\n                        \'>, <IfNode>, <TextNode: u\'\\n                        \'>]>, <TextNode: u\'\\n                        \'>, <Block Node: nav-global. Contents: []>, <TextNode: u\'\\n                        \'>]>}, {\'block\': <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>}]'
Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'2ib79xYiDbnkW5zTZo0cVvJzSXyFPv25nb8edNM5kllbBBqousTJwYi3zb1SXUAl\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398f7ea90>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e91390>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398f7e710>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398fbbdd0>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post">\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f9398e87cd0>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398e87f50>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x7f9398e89550>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398e89950>, <TextNode: u\'" /></li>\\n               \'>]>}]'
Exception while resolving variable 'error_message' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'2ib79xYiDbnkW5zTZo0cVvJzSXyFPv25nb8edNM5kllbBBqousTJwYi3zb1SXUAl\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398f7ea90>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e91390>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398f7e710>, u\'request\': <WSGIRequest: GET \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=False, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398fbbdd0>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post">\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f9398e87cd0>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398e87f50>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x7f9398e89550>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398e89950>, <TextNode: u\'" /></li>\\n               \'>]>}]'
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 5786
"GET /static/grappelli/jquery/ui/jquery-ui.min.css HTTP/1.1" 200 30163
"GET /static/grappelli/stylesheets/mueller/grid/output.css HTTP/1.1" 200 36537
"GET /static/grappelli/js/grappelli.min.js HTTP/1.1" 200 25765
"GET /static/grappelli/jquery/jquery-2.1.4.min.js HTTP/1.1" 200 84345
"GET /static/grappelli/stylesheets/screen.css HTTP/1.1" 200 163277
"GET /static/grappelli/jquery/ui/jquery-ui.min.js HTTP/1.1" 200 240427
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'admin'; args=(u'admin',)
Exception while resolving variable 'debug' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [debug] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f9398efd848>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e89710>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f939859b890>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47590>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47650>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: javascripts. Contents: [<TextNode: u\'\\n        <script type="te\'>, <django.template.defaulttags.FilterNode object at 0x7f9398eb2b10>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.FilterNode object at 0x7f9398eb2c10>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.URLNode object at 0x7f9398eae9d0>, <TextNode: u\'",\\n                MODEL_\'>, <IfNode>, <TextNode: u\',\\n                DATE_FO\'>, <django.template.library.SimpleNode object at 0x7f9398eaec50>, <TextNode: u\'",\\n                TIME_F\'>, <django.template.library.SimpleNode object at 0x7f9398eaecd0>, <TextNode: u\'",\\n                DATETI\'>, <django.template.library.SimpleNode object at 0x7f9398eaed50>, <TextNode: u\'";\\n        </script>\\n    \'>, <django.template.library.SimpleNode object at 0x7f9398eaedd0>, <TextNode: u\'" type="text/javascript">\'>, <django.template.library.SimpleNode object at 0x7f9398eaee90>, <TextNode: u\'" type="text/javascript">\'>, <IfNode>, <TextNode: u\'\\n        <script type="te\'>]>}]'
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f9398efd848>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e89710>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f939859b890>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47590>, u'request': <WSGIRequest: POST '/admin/login/?next=/admin/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/', 'available_apps': [], 'site_name': '192.168.1.34:8000', 'form': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, 'site': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47650>, 'next': u'/admin/', 'site_title': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u'LANGUAGE_CODE': 'zh-Hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False}]"
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f9398efd848>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e89710>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f939859b890>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47590>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47650>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}]'
Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f9398efd848>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e89710>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f939859b890>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47590>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47650>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}, {\'block\': <Block Node: navigation. Contents: [<TextNode: u\'\\n                        \'>, <Block Node: branding. Contents: []>, <TextNode: u\'\\n                        \'>, <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>, <TextNode: u\'\\n                        \'>, <Block Node: user-tools. Contents: [<TextNode: u\'\\n                        \'>, <IfNode>, <TextNode: u\'\\n                        \'>]>, <TextNode: u\'\\n                        \'>, <Block Node: nav-global. Contents: []>, <TextNode: u\'\\n                        \'>]>}, {\'block\': <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>}]'
Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'KuGteqkaxOVmlqllvonV8iEpiuxeNdem5nDAiG8XeYTd0WcQ0sgsJLdTZI0rVCMC\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e89710>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f939859b890>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47590>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47650>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post">\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f9398ee4f90>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398ec1810>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x7f9398f7e5d0>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x7f939859b850>, <TextNode: u\'" /></li>\\n               \'>]>}]'
Exception while resolving variable 'error_message' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'KuGteqkaxOVmlqllvonV8iEpiuxeNdem5nDAiG8XeYTd0WcQ0sgsJLdTZI0rVCMC\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e89710>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f939859b890>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47590>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47650>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post">\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f9398ee4f90>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398ec1810>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x7f9398f7e5d0>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x7f939859b850>, <TextNode: u\'" /></li>\\n               \'>]>}]'
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 6097
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'admin'; args=(u'admin',)
Exception while resolving variable 'debug' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [debug] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f93985ab5f0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e476d0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e68590>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47850>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47150>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: javascripts. Contents: [<TextNode: u\'\\n        <script type="te\'>, <django.template.defaulttags.FilterNode object at 0x7f9398eb2b10>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.FilterNode object at 0x7f9398eb2c10>, <TextNode: u\'";</script>\\n        <scri\'>, <django.template.defaulttags.URLNode object at 0x7f9398ec0990>, <TextNode: u\'",\\n                MODEL_\'>, <IfNode>, <TextNode: u\',\\n                DATE_FO\'>, <django.template.library.SimpleNode object at 0x7f9398ec0c10>, <TextNode: u\'",\\n                TIME_F\'>, <django.template.library.SimpleNode object at 0x7f9398ec0c90>, <TextNode: u\'",\\n                DATETI\'>, <django.template.library.SimpleNode object at 0x7f9398ec0cd0>, <TextNode: u\'";\\n        </script>\\n    \'>, <django.template.library.SimpleNode object at 0x7f9398ec0d90>, <TextNode: u\'" type="text/javascript">\'>, <django.template.library.SimpleNode object at 0x7f9398ec0e50>, <TextNode: u\'" type="text/javascript">\'>, <IfNode>, <TextNode: u\'\\n        <script type="te\'>]>}]'
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f93985ab5f0>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e476d0>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e68590>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47850>, u'request': <WSGIRequest: POST '/admin/login/?next=/admin/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/', 'available_apps': [], 'site_name': '192.168.1.34:8000', 'form': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, 'site': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47150>, 'next': u'/admin/', 'site_title': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u'LANGUAGE_CODE': 'zh-Hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False}]"
Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f93985ab5f0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e476d0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e68590>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47850>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47150>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}]'
Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: <function _get_val at 0x7f93985ab5f0>>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e476d0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e68590>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47850>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47150>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: header. Contents: [<TextNode: u\'\\n            <!-- HEADER \'>, <Block Node: header-class. Contents: []>, <TextNode: u\'">\\n                \'>, <IfNode>, <TextNode: u\'\\n            </header>\\n  \'>]>}, {\'block\': <Block Node: navigation. Contents: [<TextNode: u\'\\n                        \'>, <Block Node: branding. Contents: []>, <TextNode: u\'\\n                        \'>, <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>, <TextNode: u\'\\n                        \'>, <Block Node: user-tools. Contents: [<TextNode: u\'\\n                        \'>, <IfNode>, <TextNode: u\'\\n                        \'>]>, <TextNode: u\'\\n                        \'>, <Block Node: nav-global. Contents: []>, <TextNode: u\'\\n                        \'>]>}, {\'block\': <Block Node: admin_title. Contents: [<TextNode: u\'<h1 id="grp-admin-title">\'>, <IfNode>, <TextNode: u\'</h1>\'>]>}]'
Exception while resolving variable 'grappelli_admin_title' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [grappelli_admin_title] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'exZZdjcTbhSfF8XtbldcG0Nn2VQsFtA2zqW6hz0GSrQ6kEOYGp6JhtmRJ9jFNS8i\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e476d0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e68590>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47850>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47150>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post">\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f9398eb1850>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398eb1ad0>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x7f9398e687d0>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398e68750>, <TextNode: u\'" /></li>\\n               \'>]>}]'
Exception while resolving variable 'error_message' in template 'admin/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [error_message] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'csrf_token\': <SimpleLazyObject: u\'exZZdjcTbhSfF8XtbldcG0Nn2VQsFtA2zqW6hz0GSrQ6kEOYGp6JhtmRJ9jFNS8i\'>, \'user\': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f9398e476d0>>, \'perms\': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9398e68590>, \'DEFAULT_MESSAGE_LEVELS\': {\'DEBUG\': 10, \'INFO\': 20, \'WARNING\': 30, \'SUCCESS\': 25, \'ERROR\': 40}, \'messages\': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9398e47850>, u\'request\': <WSGIRequest: POST \'/admin/login/?next=/admin/\'>}, {}, {\'username\': u\'\', \'app_path\': u\'/admin/login/?next=/admin/\', \'available_apps\': [], \'site_name\': \'192.168.1.34:8000\', \'form\': <AdminAuthenticationForm bound=True, valid=False, fields=(username;password)>, \'title\': u\'\\u767b\\u5f55\', \'site_header\': <django.utils.functional.__proxy__ object at 0x7f939d5821d0>, \'site\': <django.contrib.sites.requests.RequestSite object at 0x7f9398e47150>, \'next\': u\'/admin/\', \'site_title\': <django.utils.functional.__proxy__ object at 0x7f939d582190>, u\'LANGUAGE_CODE\': \'zh-Hans\', \'has_permission\': False, \'site_url\': \'/\', u\'LANGUAGE_BIDI\': False}, {\'block\': <Block Node: content. Contents: [<TextNode: u\'\\n    <div class="g-d-c g-\'>, <Variable Node: app_path>, <TextNode: u\'" method="post">\'>, <django.template.defaulttags.CsrfTokenNode object at 0x7f9398eb1850>, <TextNode: u\'\\n            <fieldset cl\'>, <IfNode>, <TextNode: u\'</span>\\n                 \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398eb1ad0>, <TextNode: u\'</span>\\n                <\'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    <div\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.username.label>, <TextNode: u\'</label>\\n                \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <IfNode>, <TextNode: u\'">\\n                      \'>, <Variable Node: form.password.label>, <TextNode: u\'</label>\\n                \'>, <Variable Node: next>, <TextNode: u\'" />\\n                    \'>, <IfNode>, <TextNode: u\'\\n                    </di\'>, <django.template.defaulttags.URLNode object at 0x7f9398e687d0>, <TextNode: u\'\\n                    \'>, <IfNode>, <TextNode: u\'\\n                </div>\\n \'>, <django.templatetags.i18n.TranslateNode object at 0x7f9398e68750>, <TextNode: u\'" /></li>\\n               \'>]>}]'
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 6097
"GET / HTTP/1.1" 302 0
"GET /updateOp/login HTTP/1.1" 200 3274
(0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.001) SELECT VERSION(); args=None
(0.000) SET SQL_AUTO_IS_NULL = 0; args=None
(0.002) SHOW FULL TABLES; args=None
(0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
